name: CI Unit Testing Workflow

on:
  pull_request:
    paths:
      - '5-laboratorio-testing/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install
        run: |
          npm ci
          npm install @rollup/rollup-linux-x64-gnu --save-optional
      - name: Unit tests
        run: npm test
